name: GitHub Enterprise Invitation Action

inputs:
  token:
    required: true
  org:
    required: false
  enterprise: 
    required: false
  sort:
    # Sort by: login, email, state, created_at, failed_at, inviter, entOrg
    required: false
    default: 'created_at'
  committer-name:
    description: 'The name of the committer that will appear in the Git history'
    default: 'github-actions'
    required: false
  committer-email:
    description: 'The committer email that will appear in the Git history'
    default: 'github-actions@github.com'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
  